
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 11 16:03:58 CET 2024
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 23;
  public static final int ASSIGNMENT = 6;
  public static final int INTEGER = 25;
  public static final int GREATER = 14;
  public static final int OUT = 28;
  public static final int MINUS = 9;
  public static final int SEMICOLON = 4;
  public static final int IS = 26;
  public static final int AND = 16;
  public static final int RECORD = 31;
  public static final int TYPE = 35;
  public static final int COMMA = 7;
  public static final int BEGIN = 17;
  public static final int LOOP = 27;
  public static final int MULTIPLY = 8;
  public static final int IF = 24;
  public static final int DOT = 13;
  public static final int CLOSEPARENTHESIS = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 32;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int DISTINCT = 15;
  public static final int NUMBER = 12;
  public static final int CONSTANT = 19;
  public static final int PUTLINE = 30;
  public static final int OPENPARENTHESIS = 2;
  public static final int COLON = 5;
  public static final int ELSE = 20;
  public static final int WHILE = 36;
  public static final int THEN = 33;
  public static final int END = 21;
  public static final int STRING = 11;
  public static final int FALSE = 22;
  public static final int PROCEDURE = 29;
  public static final int IDENTIFIER = 10;
}

